#!/bin/bash
#
# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

DEVICE=kltedcmactive
VENDOR=samsung

MY_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$MY_DIR" ]]; then MY_DIR="$PWD"; fi

ANDROID_ROOT="$MY_DIR"/../../..

HELPER="$ANDROID_ROOT"/vendor/lineage/build/tools/extract_utils.sh
if [ -f "$HELPER" ]; then
    . "$HELPER"

    write_headers
    write_makefiles "$MY_DIR"/proprietary-files.txt
    write_footers
else
    # Standalone setup-makefiles mode
    echo "[*] Writing vendor makefiles (standalone mode)..."
    VENDOR_DIR="$ANDROID_ROOT/vendor/$VENDOR/$DEVICE"
    mkdir -p "$VENDOR_DIR"

    # BoardConfigVendor.mk
    cat << EOF > "$VENDOR_DIR/BoardConfigVendor.mk"
# Generated by setup-makefiles.sh
EOF

    # Android.mk
    cat << EOF > "$VENDOR_DIR/Android.mk"
# Generated by setup-makefiles.sh
LOCAL_PATH := \$(call my-dir)

ifeq (\$(TARGET_DEVICE),$DEVICE)
include \$(CLEAR_VARS)
LOCAL_MODULE := \$(TARGET_DEVICE)-vendor
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := FAKE
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_SYSTEM)/base_rules.mk
endif
EOF

    # $DEVICE-vendor.mk
    cat << "EOF" > "$VENDOR_DIR/$DEVICE-vendor.mk"
# Generated by setup-makefiles.sh
$(call inherit-product, $(SRC_TARGET_DIR)/product/languages_full.mk)

PRODUCT_COPY_FILES += \
EOF

    while IFS= read -r line || [ -n "$line" ]; do
        line=$(echo "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
        [[ "$line" =~ ^#.*$ ]] && continue
        [[ -z "$line" ]] && continue

        clean_entry="${line%%|*}"
        if [[ "$clean_entry" == *":"* ]]; then
            dst_file="${clean_entry##*:}"
        else
            dst_file="$clean_entry"
        fi
        dst_file="${dst_file#-}"

        echo "    vendor/$VENDOR/$DEVICE/proprietary/$dst_file:$dst_file \\" >> "$VENDOR_DIR/$DEVICE-vendor.mk"
    done < "$MY_DIR"/proprietary-files.txt

    # Remove trailing backslash from last line
    sed -i '$ s/\\$//' "$VENDOR_DIR/$DEVICE-vendor.mk"

    echo "[+] Vendor makefiles successfully generated in $VENDOR_DIR"
fi
