#
# GPS Configuration for NTT docomo Galaxy S5 Active (SC-02G)
#
NTP_SERVER=ntp.nict.jp
NTP_SERVER=jp.pool.ntp.org
NTP_SERVER=0.jp.pool.ntp.org
NTP_SERVER=time.google.com

AGPS_SERVER=supl.google.com
SUPL_HOST=supl.google.com
SUPL_PORT=7275
SUPL_VER=0x20000
SUPL_MODE=1

INTERMEDIATE_POS=1
ACCURACY_THRES=5000
REPORT_POSITION_TO_APP=1

# Qualcomm GNSS features
ENABLE_WIPER=0
CAPABILITIES=0x37
DEBUG_LEVEL=3
