###############################################################################
# NXP PN547 NFC Configuration for Samsung Galaxy S5 Active (SC-02G)
###############################################################################
NXPLOG_EXTNS_LOGLEVEL=0x02
NXPLOG_NCIHAL_LOGLEVEL=0x02
NXPLOG_NCIX_LOGLEVEL=0x02
NXPLOG_NCIR_LOGLEVEL=0x02
NXPLOG_FWDNLD_LOGLEVEL=0x02
NXPLOG_TML_LOGLEVEL=0x02

# NXP FW download mode (0x01: enable, 0x00: disable)
NXP_FW_NAME="/vendor/firmware/libpn547_fw.so"
NXP_FW_PROT_SET=0x01

# I2C driver connection for PN547
NXP_SYS_CLK_FREQ_SEL=0x00
NXP_CLK_REQ_ACT_LOW=0x00
